In [10]:
import pandas as pd
data=pd.read_csv("DatasetSheet1.csv")
df=pd.DataFrame(data)
df.head(10)

  Employee Department Quarter  Score
0     Amit      Sales      Q1     78
1    Priya         HR      Q1     85
2     John         IT      Q1     92
3     Sara    Finance      Q1     88
4    David      Sales      Q2     95
5    Meera         HR      Q2     80
6     Alex         IT      Q2     70
7     Ravi    Finance      Q2     90
8     Neha      Sales      Q3     99
9    Karan         IT      Q3     76

In [11]:
df[df["Score"]>90]

  Employee Department Quarter  Score
2     John         IT      Q1     92
4    David      Sales      Q2     95
8     Neha      Sales      Q3     99

In [12]:
df[df["Department"]=="Sales"]

  Employee Department Quarter  Score
0     Amit      Sales      Q1     78
4    David      Sales      Q2     95
8     Neha      Sales      Q3     99

In [13]:
df

  Employee Department Quarter  Score
0     Amit      Sales      Q1     78
1    Priya         HR      Q1     85
2     John         IT      Q1     92
3     Sara    Finance      Q1     88
4    David      Sales      Q2     95
5    Meera         HR      Q2     80
6     Alex         IT      Q2     70
7     Ravi    Finance      Q2     90
8     Neha      Sales      Q3     99
9    Karan         IT      Q3     76

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Employee    10 non-null     object
 1   Department  10 non-null     object
 2   Quarter     10 non-null     object
 3   Score       10 non-null     int64
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes

In [15]:
df.describe()

           Score
count  10.000000
mean   85.300000
std     9.177872
min    70.000000
25%    78.500000
50%    86.500000
75%    91.500000
max    99.000000

In [16]:
df.sort_values("Department").sort_values("Score")

  Employee Department Quarter  Score
6     Alex         IT      Q2     70
9    Karan         IT      Q3     76
0     Amit      Sales      Q1     78
5    Meera         HR      Q2     80
1    Priya         HR      Q1     85
3     Sara    Finance      Q1     88
7     Ravi    Finance      Q2     90
2     John         IT      Q1     92
4    David      Sales      Q2     95
8     Neha      Sales      Q3     99

In [17]:
df.groupby("Department")["Score"].mean()

Department
Finance    89.000000
HR         82.500000
IT         79.333333
Sales      90.666667
Name: Score, dtype: float64

In [18]:
df.groupby("Department")["Score"].max()

Department
Finance    90
HR         85
IT         92
Sales      99
Name: Score, dtype: int64